# Generated by Django 2.2 on 2019-04-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='UrlShort',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=True
                                  )),
                ('url', models.CharField(max_length=250)),
                ('count', models.BigIntegerField(default=0))
            ],
        ),
    ]
