export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const SET_INGREDIENT_FISH = "SET_INGREDIENT_FISH";
export const ADD_ROLL = "ADD_ROLL";

export const PURCHASE_SUSHI_START = "PURCHASE_SUSHI_START";
export const PURCHASE_SUSHI_SUCCESS = "PURCHASE_SUSHI_SUCCESS";
export const PURCHASE_SUSHI_FAIL = "PURCHASE_SUSHI_FAIL";

export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const PURCHASE_SUSHI = "PURCHASE_SUSHI";

export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_INITTIATE_LOGOUT = "AUTH_INITTIATE_LOGOUT";

export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const INIT_SUSHI_ITEMS = "INIT_SUSHI_ITEMS";
export const SET_SUSHI_ITEMS = "SET_SUSHI_ITEMS";
export const FETCH_ITEMS_FAILED = "FETCH_ITEMS_FAILED";

export const DELETE_ITEM_FAILED = "DELETE_ITEM_FAILED";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_START = "DELETE_ITEM_START";

export const ADD_ITEM_CART_FAILED = "ADD_ITEM_CART_FAILED";
export const ADD_ITEM_CART_SUCCESS = "ADD_ITEM_CART_SUCCESS";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";

export const FETCH_CART = "FETCH_CART";
export const FETCH_CART_FAILED = "FETCH_CART_FAILED";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";

export const START_FETCH_CART = "START_FETCH_CART";
